[project]
name = "avito-tech"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.15",
    "aioresponses>=0.7.8",
    "pook>=2.1.4",
    "pytest>=8.4.2",
    "pytest-aiohttp>=1.1.0",
    "ruff>=0.13.2",
]
