name : avito-tech

on:
  push:
    paths:
      - 'avito-tech/**'

jobs:
    build:
        runs-on: ubuntu-latest
        steps:

            - uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v5

            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                    python-version: '3.x'
            - name: Install the project
              run: make install

            - name: Run linter
              run: make lint

            - name: Run tests
              run: make test
